# Copyright 2026 Precision AI
# SPDX-License-Identifier: Apache-2.0

from precisionai.agrieval.emb.metrics.analysis import analyze_embedding_space, compare_embedding_spaces
from precisionai.agrieval.emb.metrics.cross_model import (
    knn_jaccard_at_k,
    knn_overlap_at_k,
    pairwise_similarity_correlation,
    per_item_neighbor_disagreement,
)
from precisionai.agrieval.emb.metrics.duplicates import (
    duplicate_groups_at_threshold,
    duplicate_pairs_at_threshold,
)
from precisionai.agrieval.emb.metrics.geometry import (
    alignment,
    anisotropy_summary,
    centroid_similarity_stats,
    effective_rank,
    pca_explained_variance,
    uniformity,
)
from precisionai.agrieval.emb.metrics.label_aware import (
    ImageItem,
    intra_inter_similarity_gap,
    knn_confusion_matrix,
    knn_label_mrr_at_k,
    knn_label_ndcg_at_k,
    knn_label_purity_at_k,
    knn_label_r_precision,
    knn_map_at_k,
    knn_metadata_map_at_k,
    knn_metadata_mrr_at_k,
    knn_metadata_ndcg_at_k,
    knn_metadata_precision_at_k,
    knn_metadata_r_precision,
    knn_per_attribute_ndcg_at_k,
    relevance_grade,
)
from precisionai.agrieval.emb.metrics.neighbors import (
    gini_coefficient,
    hubness_at_k,
    knn_radius_at_k,
    mean_top_k_similarity,
    outlier_score_at_k,
)
from precisionai.agrieval.emb.metrics.ranking import (
    average_precision_at_k,
    dcg_at_k,
    l2_normalize,
    ndcg_at_k,
    normalize_ks,
    precision_at_k,
    r_precision,
    recall_at_k,
    reciprocal_rank,
    safe_mean,
)
from precisionai.agrieval.emb.metrics.separation import (
    calinski_harabasz,
    kmeans_label_agreement,
    pc1_auroc,
    silhouette_cosine,
)
from precisionai.agrieval.emb.metrics.similarity import (
    cosine_similarity_matrix,
    pairwise_similarity_stats,
    similarity_threshold_counts,
    top_k_neighbors,
)

__all__ = [
    "ImageItem",
    "alignment",
    "analyze_embedding_space",
    "anisotropy_summary",
    "average_precision_at_k",
    "calinski_harabasz",
    "centroid_similarity_stats",
    "compare_embedding_spaces",
    "cosine_similarity_matrix",
    "dcg_at_k",
    "duplicate_groups_at_threshold",
    "duplicate_pairs_at_threshold",
    "effective_rank",
    "gini_coefficient",
    "hubness_at_k",
    "intra_inter_similarity_gap",
    "kmeans_label_agreement",
    "knn_confusion_matrix",
    "knn_jaccard_at_k",
    "knn_label_mrr_at_k",
    "knn_label_ndcg_at_k",
    "knn_label_purity_at_k",
    "knn_label_r_precision",
    "knn_map_at_k",
    "knn_metadata_map_at_k",
    "knn_metadata_mrr_at_k",
    "knn_metadata_ndcg_at_k",
    "knn_metadata_precision_at_k",
    "knn_metadata_r_precision",
    "knn_overlap_at_k",
    "knn_per_attribute_ndcg_at_k",
    "knn_radius_at_k",
    "l2_normalize",
    "mean_top_k_similarity",
    "ndcg_at_k",
    "normalize_ks",
    "outlier_score_at_k",
    "pairwise_similarity_correlation",
    "pairwise_similarity_stats",
    "pc1_auroc",
    "pca_explained_variance",
    "per_item_neighbor_disagreement",
    "precision_at_k",
    "r_precision",
    "recall_at_k",
    "reciprocal_rank",
    "relevance_grade",
    "safe_mean",
    "silhouette_cosine",
    "similarity_threshold_counts",
    "top_k_neighbors",
    "uniformity",
]
