name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  unit-tests:
    uses: ./.github/workflows/unit-test.yml
